/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (PostgreSQL reachable) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a demo session
         * @description Checks the configured demo credential and sets the `bia_session` cookie.
         *     Requires Content-Type application/json (charset parameters are accepted)
         *     and exactly one JSON object, with no unknown fields or trailing data.
         *     The entire body, including whitespace, is limited to 4096 bytes.
         *     Invalid media type, malformed or oversized bodies return 400 invalid_request.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Expires the session cookie. Idempotent; works with or without a valid session. There is no server-side revocation.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meters with their current analytical state */
        get: operations["listMeters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meters/{meterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meter detail */
        get: operations["getMeter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meters/{meterId}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reading history of a meter
         * @description Readings in the half-open range [`from`, `to`), in time order.
         */
        get: operations["listMeterReadings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings of the latest completed run, by priority */
        get: operations["listAnomalies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/anomalies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A finding with its structured evidence
         * @description Returns what the analysis run stored; nothing is recomputed and no LLM is called.
         */
        get: operations["getAnomaly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queue an analysis run
         * @description Queues a run and returns immediately; a background worker executes it.
         *     At most one run is active: while a QUEUED or RUNNING run exists, the
         *     same run is returned with `created: false` (guaranteed by the database).
         */
        post: operations["requestAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/analysis/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State of an analysis run (poll until COMPLETED or FAILED) */
        get: operations["getAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fleet summary
         * @description Source figures always; analytical figures only from the latest
         *     completed run. Before any run completes: `anomalies` and
         *     `high_priority` are 0 and `aggregate_confidence` and
         *     `latest_analysis` are null.
         */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The only error shape. Other codes include `not_found`, `method_not_allowed`, `request_timeout` (503) and `internal_error` (500). */
        Error: {
            error: {
                /** @description Stable machine-readable code. */
                code: string;
                /** @description Safe human-readable text; never internals. */
                message: string;
                /** @description Same value as the X-Request-ID response header. */
                request_id: string;
            };
        };
        Health: {
            status: string;
            checks?: {
                [key: string]: string;
            };
        };
        /**
         * @description Source wall-clock time without offset (the dataset has no time zone). Not UTC.
         * @example 2026-09-12T14:00:00
         */
        SourceTime: string;
        /**
         * Format: date-time
         * @description Platform instant, RFC 3339 in UTC.
         * @example 2026-09-24T23:18:00Z
         */
        SystemTime: string;
        /**
         * @description Analytical meter status (never the source `status` column).
         * @enum {string}
         */
        ComputedStatus: "OK" | "ALERT" | "CRITICAL";
        /** @enum {string} */
        AnomalyType: "REAL_ANOMALY" | "DATA_QUALITY" | "EXPLAINABLE_ANOMALY" | "FALSE_POSITIVE";
        /** @enum {string} */
        Severity: "HIGH" | "MEDIUM" | "LOW";
        /** @enum {string} */
        RecommendedAction: "INVESTIGATE_METER_AND_INSTALLATION" | "VALIDATE_MEASUREMENT_OR_SENSOR" | "VALIDATE_OPERATIONAL_CHANGE" | "NO_ESCALATION_MONITOR";
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        Session: {
            authenticated: boolean;
            username: string;
            expires_at: components["schemas"]["SystemTime"];
        };
        Pagination: {
            limit: number;
            offset: number;
            /** @description Matching items across all pages. */
            total: number;
        };
        /** @description The latest completed run that produced the current state. */
        AnalysisRef: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            status: "COMPLETED";
            completed_at: components["schemas"]["SystemTime"];
        };
        Period: {
            first_reading_at: components["schemas"]["SourceTime"];
            last_reading_at: components["schemas"]["SourceTime"];
        };
        MeterSummary: {
            meter_id: string;
            /** @description Sum over all readings of the meter. */
            total_consumption_kwh: number;
            /** @description Consumption deviation of the meter's top finding over its episode (observed vs baseline energy); null without a finding. */
            variation_pct: number | null;
            /** @description Null before any run completes. */
            computed_status: components["schemas"]["ComputedStatus"] | null;
            /** Format: int64 */
            anomaly_id: number | null;
            anomaly_type: components["schemas"]["AnomalyType"] | null;
            severity: components["schemas"]["Severity"] | null;
            confidence: number | null;
            priority: number | null;
        };
        MeterList: {
            items: components["schemas"]["MeterSummary"][];
            pagination: components["schemas"]["Pagination"];
            analysis: components["schemas"]["AnalysisRef"] | null;
        };
        MeterFinding: {
            /** Format: int64 */
            anomaly_id: number;
            type: components["schemas"]["AnomalyType"];
            severity: components["schemas"]["Severity"];
            confidence: number;
            priority: number;
            variation_pct: number;
            started_at: components["schemas"]["SourceTime"];
            last_observed_at: components["schemas"]["SourceTime"];
            recommended_action: components["schemas"]["RecommendedAction"];
            reason: string;
        };
        MeterDetail: {
            meter_id: string;
            total_consumption_kwh: number;
            readings_count: number;
            period: components["schemas"]["Period"] | null;
            computed_status: components["schemas"]["ComputedStatus"] | null;
            /** @description Findings of this meter in the current run. */
            findings_count: number;
            /** @description Highest-priority finding of the meter. */
            current_finding: components["schemas"]["MeterFinding"] | null;
            analysis: components["schemas"]["AnalysisRef"] | null;
        };
        Reading: {
            timestamp: components["schemas"]["SourceTime"];
            consumption_kwh: number;
            voltage_v: number;
            current_a: number;
            power_factor: number;
            /** @description The CSV status column as supplied; not meter health. */
            source_status: string;
        };
        ReadingList: {
            meter_id: string;
            from: components["schemas"]["SourceTime"] | null;
            to: components["schemas"]["SourceTime"] | null;
            limit: number;
            has_more: boolean;
            items: components["schemas"]["Reading"][];
        };
        AnomalySummary: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            analysis_id: number;
            meter_id: string;
            /** @description 1 is investigated first. */
            priority: number;
            type: components["schemas"]["AnomalyType"];
            severity: components["schemas"]["Severity"];
            confidence: number;
            /** @enum {string} */
            status: "OPEN";
            started_at: components["schemas"]["SourceTime"];
            last_observed_at: components["schemas"]["SourceTime"];
            duration_hours: number;
            /** @description Observed vs baseline energy over the episode, in percent. */
            variation_pct: number;
            /** @description Deterministic one-sentence summary built only from the evidence. */
            reason: string;
            recommended_action: components["schemas"]["RecommendedAction"];
        };
        AnomalyList: {
            items: components["schemas"]["AnomalySummary"][];
            pagination: components["schemas"]["Pagination"];
            analysis: components["schemas"]["AnalysisRef"] | null;
        };
        AnomalyDetail: components["schemas"]["AnomalySummary"] & {
            /** @description Decision path that produced the type. */
            rule: string;
            created_at: components["schemas"]["SystemTime"];
            evidence: components["schemas"]["Evidence"];
        };
        /** @description Structured evidence persisted by the analysis run (schema_version 1). Correlated events are in `related_events`. */
        Evidence: {
            /** @constant */
            schema_version: 1;
            rule: string;
            /** @description Median primary deviation as a multiple of its threshold. */
            evidence_strength: number;
            consumption: {
                baseline_kwh: number;
                observed_kwh: number;
                deviation_pct: number;
                median_deviation_pct: number;
                /** @enum {string} */
                direction: "UP" | "DOWN";
            };
            persistence: {
                duration_hours: number;
                flagged_readings: number;
                span_readings: number;
                density_fraction: number;
                longest_run: number;
                sustained: boolean;
                recovery: {
                    recovered: boolean;
                    recovered_at: components["schemas"]["SourceTime"] | null;
                    readings_observed: number;
                    median_consumption_deviation_pct: number;
                };
            };
            metrics: {
                /** @enum {string} */
                metric: "consumption_kwh" | "voltage_v" | "current_a" | "power_factor" | "consumption_to_load_proxy_ratio";
                evaluated_readings: number;
                triggered_readings: number;
                median_observed: number;
                median_baseline: number;
                median_deviation_pct: number;
                max_abs_deviation_pct: number;
                /** @enum {string|null} */
                direction: "UP" | "DOWN" | "MIXED" | null;
                corroborates: boolean;
            }[];
            related_events: {
                timestamp: components["schemas"]["SourceTime"];
                type: string;
                description: string;
                /** @description Event time minus the episode onset. */
                offset_seconds: number;
                /** @enum {string} */
                role: "EXPLAINS" | "CORROBORATES" | "CONTEXT";
            }[];
            confidence_breakdown: {
                signal_strength: number;
                persistence: number;
                multivariate_support: number;
                event_context: number;
                pattern_support: number;
            };
            signals: {
                metric: string;
                timestamp: components["schemas"]["SourceTime"];
                observed: number;
                baseline: number;
                deviation: number;
                deviation_pct: number;
                robust_z: number;
                /** @enum {string} */
                direction: "UP" | "DOWN";
                strength: number;
            }[];
        };
        AnalysisRun: {
            /** Format: int64 */
            analysis_id: number;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
            /**
             * @description Real lifecycle step; progress is 0, 10, 35, 85, 100 at QUEUED, LOADING_DATA, ANALYZING, PERSISTING_RESULTS, COMPLETED. A FAILED run keeps the progress of the stage that failed.
             * @enum {string}
             */
            stage: "QUEUED" | "LOADING_DATA" | "ANALYZING" | "PERSISTING_RESULTS" | "COMPLETED" | "FAILED";
            progress: number;
            engine_version: string;
            created_at: components["schemas"]["SystemTime"];
            started_at: components["schemas"]["SystemTime"] | null;
            completed_at: components["schemas"]["SystemTime"] | null;
            meters_count: number | null;
            readings_count: number | null;
            events_count: number | null;
            findings_count: number | null;
            /** @description Findings with severity HIGH. */
            high_priority_count: number | null;
            /** @description Mean confidence of the run's findings; null without findings. */
            aggregate_confidence: number | null;
            error: null | {
                /** @enum {string} */
                code: "load_failed" | "analysis_failed" | "persistence_failed" | "timeout" | "interrupted";
                message: string;
            };
        };
        AnalyzeResponse: components["schemas"]["AnalysisRun"] & {
            /** @description False when the already active run was returned. */
            created: boolean;
        };
        DashboardSummary: {
            meters: number;
            readings: number;
            /** @description Sum over all readings of the period. */
            total_consumption_kwh: number;
            period: components["schemas"]["Period"] | null;
            /** @description Findings of the latest completed run (all types). */
            anomalies: number;
            /** @description Of those, findings with severity HIGH. */
            high_priority: number;
            /** @description Mean confidence of those findings; null before any completed run or without findings. */
            aggregate_confidence: number | null;
            latest_analysis: components["schemas"]["AnalysisRef"] | null;
            active_analysis: null | {
                /** Format: int64 */
                id: number;
                /** @enum {string} */
                status: "QUEUED" | "RUNNING";
                stage: string;
                progress: number;
            };
        };
    };
    responses: {
        /** @description Invalid input (`invalid_query`, `invalid_meter_id`, `invalid_anomaly_id`, `invalid_analysis_id`, `invalid_timestamp`, `invalid_range`, `invalid_request`). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No valid session (`unauthorized`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "unauthorized",
                 *         "message": "Authentication is required.",
                 *         "request_id": "3f2a9c0e5b7d41e8a6c4b2d0f1e3a5c7"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown resource (`meter_not_found`, `anomaly_not_found`, `analysis_not_found`). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Limit: number;
        Offset: number;
        /** @example M-109 */
        MeterId: string;
        AnomalyId: number;
        AnalysisId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process can serve HTTP. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PostgreSQL is reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready",
                     *       "checks": {
                     *         "postgres": "ok"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description PostgreSQL is not reachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "not_ready",
                     *       "checks": {
                     *         "postgres": "unavailable"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; the session cookie is set. */
            200: {
                headers: {
                    /** @description `bia_session=...; Path=/; HttpOnly; SameSite=Lax` (and `Secure` unless disabled). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid credentials (`invalid_credentials`). The message never says which field was wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request carries a valid session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMeters: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring of the meter ID (at most 64 characters, matched literally). */
                search?: string;
                /** @description Computed status of the latest completed run. */
                status?: components["schemas"]["ComputedStatus"];
                /** @description `variation` sorts by magnitude; meters without a value sort last. `severity` sorts by severity, then priority. */
                sort?: "meter_id" | "consumption" | "variation" | "severity";
                /** @description Default is `asc` for `meter_id` and `desc` for the other sort keys. */
                order?: "asc" | "desc";
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of meters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeterList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getMeter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example M-109 */
                meterId: components["parameters"]["MeterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The meter. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeterDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listMeterReadings: {
        parameters: {
            query?: {
                /** @description Inclusive start (source time, no offset). */
                from?: components["schemas"]["SourceTime"];
                /** @description Exclusive end (source time, no offset). Must not be earlier than `from`. */
                to?: components["schemas"]["SourceTime"];
                limit?: number;
            };
            header?: never;
            path: {
                /** @example M-109 */
                meterId: components["parameters"]["MeterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readings; `has_more` reports truncation by `limit`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAnomalies: {
        parameters: {
            query?: {
                meter_id?: string;
                type?: components["schemas"]["AnomalyType"];
                severity?: components["schemas"]["Severity"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page ordered by priority (1 first). Empty before any run completes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAnomaly: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AnomalyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The finding. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    requestAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run queued (or the active run returned). */
            202: {
                headers: {
                    /** @description `/api/v1/ai/analysis/{id}` */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AnalysisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
