// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis_runs.sql

package dbgen

import (
	"context"
	"time"
)

const claimQueuedAnalysisRun = `-- name: ClaimQueuedAnalysisRun :one
UPDATE analysis_runs
SET status = 'RUNNING', stage = 'LOADING_DATA', progress_percent = $1, started_at = now(),
    engine_version = $2, configuration = $3
WHERE id = (
    SELECT q.id FROM analysis_runs q
    WHERE q.status = 'QUEUED'
    ORDER BY q.id
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, status, stage, progress_percent, engine_version, configuration,
          meters_count, readings_count, events_count, findings_count, high_priority_count, aggregate_confidence,
          error_code, error_message, created_at, started_at, completed_at
`

type ClaimQueuedAnalysisRunParams struct {
	ProgressPercent int16
	EngineVersion   string
	Configuration   []byte
}

// Atomically moves the oldest QUEUED run to RUNNING. SKIP LOCKED lets
// competing workers pass over a run another worker is claiming.
func (q *Queries) ClaimQueuedAnalysisRun(ctx context.Context, arg ClaimQueuedAnalysisRunParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, claimQueuedAnalysisRun, arg.ProgressPercent, arg.EngineVersion, arg.Configuration)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.ProgressPercent,
		&i.EngineVersion,
		&i.Configuration,
		&i.MetersCount,
		&i.ReadingsCount,
		&i.EventsCount,
		&i.FindingsCount,
		&i.HighPriorityCount,
		&i.AggregateConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeAnalysisRun = `-- name: CompleteAnalysisRun :execrows
UPDATE analysis_runs
SET status = 'COMPLETED', stage = 'COMPLETED', progress_percent = 100,
    findings_count = $1, high_priority_count = $2,
    aggregate_confidence = $3,
    completed_at = now()
WHERE id = $4 AND status = 'RUNNING'
`

type CompleteAnalysisRunParams struct {
	FindingsCount       *int32
	HighPriorityCount   *int32
	AggregateConfidence *float64
	ID                  int64
}

func (q *Queries) CompleteAnalysisRun(ctx context.Context, arg CompleteAnalysisRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAnalysisRun,
		arg.FindingsCount,
		arg.HighPriorityCount,
		arg.AggregateConfidence,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAnalysisRun = `-- name: CreateAnalysisRun :one

INSERT INTO analysis_runs (engine_version, configuration)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING id, status, stage, progress_percent, engine_version, configuration,
          meters_count, readings_count, events_count, findings_count, high_priority_count, aggregate_confidence,
          error_code, error_message, created_at, started_at, completed_at
`

type CreateAnalysisRunParams struct {
	EngineVersion string
	Configuration []byte
}

// Analysis run lifecycle and result persistence (internal/analysisrun).
// Inserts a QUEUED run unless another run is active; the partial unique
// index analysis_runs_single_active then makes this return no row.
func (q *Queries) CreateAnalysisRun(ctx context.Context, arg CreateAnalysisRunParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, createAnalysisRun, arg.EngineVersion, arg.Configuration)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.ProgressPercent,
		&i.EngineVersion,
		&i.Configuration,
		&i.MetersCount,
		&i.ReadingsCount,
		&i.EventsCount,
		&i.FindingsCount,
		&i.HighPriorityCount,
		&i.AggregateConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failAnalysisRun = `-- name: FailAnalysisRun :execrows
UPDATE analysis_runs
SET status = 'FAILED', stage = 'FAILED', error_code = $1, error_message = $2,
    completed_at = now()
WHERE id = $3 AND status IN ('QUEUED', 'RUNNING')
`

type FailAnalysisRunParams struct {
	ErrorCode    *string
	ErrorMessage *string
	ID           int64
}

func (q *Queries) FailAnalysisRun(ctx context.Context, arg FailAnalysisRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAnalysisRun, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failInterruptedAnalysisRuns = `-- name: FailInterruptedAnalysisRuns :many
UPDATE analysis_runs
SET status = 'FAILED', stage = 'FAILED', error_code = $1, error_message = $2,
    completed_at = now()
WHERE status = 'RUNNING'
RETURNING id
`

type FailInterruptedAnalysisRunsParams struct {
	ErrorCode    *string
	ErrorMessage *string
}

// Startup recovery: a RUNNING run cannot still be running after a restart.
func (q *Queries) FailInterruptedAnalysisRuns(ctx context.Context, arg FailInterruptedAnalysisRunsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, failInterruptedAnalysisRuns, arg.ErrorCode, arg.ErrorMessage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveAnalysisRun = `-- name: GetActiveAnalysisRun :one
SELECT id, status, stage, progress_percent, engine_version, configuration,
       meters_count, readings_count, events_count, findings_count, high_priority_count, aggregate_confidence,
       error_code, error_message, created_at, started_at, completed_at
FROM analysis_runs
WHERE status IN ('QUEUED', 'RUNNING')
`

func (q *Queries) GetActiveAnalysisRun(ctx context.Context) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, getActiveAnalysisRun)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.ProgressPercent,
		&i.EngineVersion,
		&i.Configuration,
		&i.MetersCount,
		&i.ReadingsCount,
		&i.EventsCount,
		&i.FindingsCount,
		&i.HighPriorityCount,
		&i.AggregateConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAnalysisRun = `-- name: GetAnalysisRun :one
SELECT id, status, stage, progress_percent, engine_version, configuration,
       meters_count, readings_count, events_count, findings_count, high_priority_count, aggregate_confidence,
       error_code, error_message, created_at, started_at, completed_at
FROM analysis_runs
WHERE id = $1
`

func (q *Queries) GetAnalysisRun(ctx context.Context, id int64) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, getAnalysisRun, id)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Stage,
		&i.ProgressPercent,
		&i.EngineVersion,
		&i.Configuration,
		&i.MetersCount,
		&i.ReadingsCount,
		&i.EventsCount,
		&i.FindingsCount,
		&i.HighPriorityCount,
		&i.AggregateConfidence,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertAnalysisMeterResult = `-- name: InsertAnalysisMeterResult :exec
INSERT INTO analysis_meter_results (
    analysis_run_id, meter_id, computed_status, evaluated_readings, flagged_readings, findings_count
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type InsertAnalysisMeterResultParams struct {
	AnalysisRunID     int64
	MeterID           string
	ComputedStatus    string
	EvaluatedReadings int32
	FlaggedReadings   int32
	FindingsCount     int32
}

func (q *Queries) InsertAnalysisMeterResult(ctx context.Context, arg InsertAnalysisMeterResultParams) error {
	_, err := q.db.Exec(ctx, insertAnalysisMeterResult,
		arg.AnalysisRunID,
		arg.MeterID,
		arg.ComputedStatus,
		arg.EvaluatedReadings,
		arg.FlaggedReadings,
		arg.FindingsCount,
	)
	return err
}

const insertAnomaly = `-- name: InsertAnomaly :exec
INSERT INTO anomalies (
    analysis_run_id, meter_id, priority, type, severity, confidence, rule,
    recommended_action, reason, started_at, last_observed_at, duration_seconds,
    consumption_deviation_pct, evidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14
)
`

type InsertAnomalyParams struct {
	AnalysisRunID           int64
	MeterID                 string
	Priority                int32
	Type                    string
	Severity                string
	Confidence              float64
	Rule                    string
	RecommendedAction       string
	Reason                  string
	StartedAt               time.Time
	LastObservedAt          time.Time
	DurationSeconds         int64
	ConsumptionDeviationPct float64
	Evidence                []byte
}

func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) error {
	_, err := q.db.Exec(ctx, insertAnomaly,
		arg.AnalysisRunID,
		arg.MeterID,
		arg.Priority,
		arg.Type,
		arg.Severity,
		arg.Confidence,
		arg.Rule,
		arg.RecommendedAction,
		arg.Reason,
		arg.StartedAt,
		arg.LastObservedAt,
		arg.DurationSeconds,
		arg.ConsumptionDeviationPct,
		arg.Evidence,
	)
	return err
}

const listAnalysisEvents = `-- name: ListAnalysisEvents :many
SELECT meter_id, event_timestamp, event_type, description
FROM events
ORDER BY meter_id, event_timestamp, id
`

type ListAnalysisEventsRow struct {
	MeterID        string
	EventTimestamp time.Time
	EventType      string
	Description    string
}

func (q *Queries) ListAnalysisEvents(ctx context.Context) ([]ListAnalysisEventsRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalysisEventsRow
	for rows.Next() {
		var i ListAnalysisEventsRow
		if err := rows.Scan(
			&i.MeterID,
			&i.EventTimestamp,
			&i.EventType,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysisReadings = `-- name: ListAnalysisReadings :many
SELECT meter_id, reading_timestamp,
       consumption_kwh::float8 AS consumption_kwh,
       voltage_v::float8       AS voltage_v,
       current_a::float8       AS current_a,
       power_factor::float8    AS power_factor
FROM readings
ORDER BY meter_id, reading_timestamp
`

type ListAnalysisReadingsRow struct {
	MeterID          string
	ReadingTimestamp time.Time
	ConsumptionKwh   float64
	VoltageV         float64
	CurrentA         float64
	PowerFactor      float64
}

// Engine input. NUMERIC → float8 rounds to the nearest double, exactly as
// parsing the source decimal text does.
func (q *Queries) ListAnalysisReadings(ctx context.Context) ([]ListAnalysisReadingsRow, error) {
	rows, err := q.db.Query(ctx, listAnalysisReadings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnalysisReadingsRow
	for rows.Next() {
		var i ListAnalysisReadingsRow
		if err := rows.Scan(
			&i.MeterID,
			&i.ReadingTimestamp,
			&i.ConsumptionKwh,
			&i.VoltageV,
			&i.CurrentA,
			&i.PowerFactor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAnalysisRunSourceCounts = `-- name: SetAnalysisRunSourceCounts :execrows
UPDATE analysis_runs
SET meters_count = $1, readings_count = $2, events_count = $3
WHERE id = $4 AND status = 'RUNNING'
`

type SetAnalysisRunSourceCountsParams struct {
	MetersCount   *int32
	ReadingsCount *int32
	EventsCount   *int32
	ID            int64
}

func (q *Queries) SetAnalysisRunSourceCounts(ctx context.Context, arg SetAnalysisRunSourceCountsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAnalysisRunSourceCounts,
		arg.MetersCount,
		arg.ReadingsCount,
		arg.EventsCount,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAnalysisRunStage = `-- name: SetAnalysisRunStage :execrows
UPDATE analysis_runs
SET stage = $1, progress_percent = $2
WHERE id = $3 AND status = 'RUNNING'
`

type SetAnalysisRunStageParams struct {
	Stage           string
	ProgressPercent int16
	ID              int64
}

func (q *Queries) SetAnalysisRunStage(ctx context.Context, arg SetAnalysisRunStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAnalysisRunStage, arg.Stage, arg.ProgressPercent, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
