// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anomalies.sql

package dbgen

import (
	"context"
	"time"
)

const countCurrentAnomalies = `-- name: CountCurrentAnomalies :one
WITH current_run AS (
    SELECT id FROM analysis_runs
    WHERE status = 'COMPLETED'
    ORDER BY completed_at DESC, id DESC
    LIMIT 1
)
SELECT count(*)
FROM anomalies a
JOIN current_run c ON a.analysis_run_id = c.id
WHERE ($1::text IS NULL OR a.meter_id = $1::text)
  AND ($2::text IS NULL OR a.type = $2::text)
  AND ($3::text IS NULL OR a.severity = $3::text)
`

type CountCurrentAnomaliesParams struct {
	MeterID  *string
	Type     *string
	Severity *string
}

func (q *Queries) CountCurrentAnomalies(ctx context.Context, arg CountCurrentAnomaliesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrentAnomalies, arg.MeterID, arg.Type, arg.Severity)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnomaly = `-- name: GetAnomaly :one
SELECT id, analysis_run_id, meter_id, priority, type, severity, confidence, rule,
       recommended_action, reason, started_at, last_observed_at, duration_seconds,
       consumption_deviation_pct, status, evidence, created_at
FROM anomalies
WHERE id = $1
`

func (q *Queries) GetAnomaly(ctx context.Context, id int64) (Anomaly, error) {
	row := q.db.QueryRow(ctx, getAnomaly, id)
	var i Anomaly
	err := row.Scan(
		&i.ID,
		&i.AnalysisRunID,
		&i.MeterID,
		&i.Priority,
		&i.Type,
		&i.Severity,
		&i.Confidence,
		&i.Rule,
		&i.RecommendedAction,
		&i.Reason,
		&i.StartedAt,
		&i.LastObservedAt,
		&i.DurationSeconds,
		&i.ConsumptionDeviationPct,
		&i.Status,
		&i.Evidence,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentAnomalies = `-- name: ListCurrentAnomalies :many

WITH current_run AS (
    SELECT id FROM analysis_runs
    WHERE status = 'COMPLETED'
    ORDER BY completed_at DESC, id DESC
    LIMIT 1
)
SELECT a.id, a.analysis_run_id, a.meter_id, a.priority, a.type, a.severity, a.confidence,
       a.status, a.started_at, a.last_observed_at, a.duration_seconds,
       a.consumption_deviation_pct, a.reason, a.recommended_action
FROM anomalies a
JOIN current_run c ON a.analysis_run_id = c.id
WHERE ($1::text IS NULL OR a.meter_id = $1::text)
  AND ($2::text IS NULL OR a.type = $2::text)
  AND ($3::text IS NULL OR a.severity = $3::text)
ORDER BY a.priority, a.id
LIMIT $5 OFFSET $4
`

type ListCurrentAnomaliesParams struct {
	MeterID   *string
	Type      *string
	Severity  *string
	RowOffset int32
	RowLimit  int32
}

type ListCurrentAnomaliesRow struct {
	ID                      int64
	AnalysisRunID           int64
	MeterID                 string
	Priority                int32
	Type                    string
	Severity                string
	Confidence              float64
	Status                  string
	StartedAt               time.Time
	LastObservedAt          time.Time
	DurationSeconds         int64
	ConsumptionDeviationPct float64
	Reason                  string
	RecommendedAction       string
}

// Anomaly list and detail (internal/anomaly). The list shows the findings of
// the latest COMPLETED run only; findings of a run become visible only when
// its completion transaction commits.
func (q *Queries) ListCurrentAnomalies(ctx context.Context, arg ListCurrentAnomaliesParams) ([]ListCurrentAnomaliesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentAnomalies,
		arg.MeterID,
		arg.Type,
		arg.Severity,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentAnomaliesRow
	for rows.Next() {
		var i ListCurrentAnomaliesRow
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisRunID,
			&i.MeterID,
			&i.Priority,
			&i.Type,
			&i.Severity,
			&i.Confidence,
			&i.Status,
			&i.StartedAt,
			&i.LastObservedAt,
			&i.DurationSeconds,
			&i.ConsumptionDeviationPct,
			&i.Reason,
			&i.RecommendedAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
