// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package dbgen

import (
	"context"
	"time"
)

const getLatestCompletedRunSummary = `-- name: GetLatestCompletedRunSummary :one
SELECT r.id, r.completed_at, r.findings_count, r.high_priority_count, r.aggregate_confidence
FROM analysis_runs r
WHERE r.status = 'COMPLETED'
ORDER BY r.completed_at DESC, r.id DESC
LIMIT 1
`

type GetLatestCompletedRunSummaryRow struct {
	ID                  int64
	CompletedAt         *time.Time
	FindingsCount       *int32
	HighPriorityCount   *int32
	AggregateConfidence *float64
}

func (q *Queries) GetLatestCompletedRunSummary(ctx context.Context) (GetLatestCompletedRunSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedRunSummary)
	var i GetLatestCompletedRunSummaryRow
	err := row.Scan(
		&i.ID,
		&i.CompletedAt,
		&i.FindingsCount,
		&i.HighPriorityCount,
		&i.AggregateConfidence,
	)
	return i, err
}

const getReadingPeriod = `-- name: GetReadingPeriod :one
SELECT min(reading_timestamp)::timestamp AS first_reading_at,
       max(reading_timestamp)::timestamp AS last_reading_at
FROM readings
WHERE $1::text IS NULL OR meter_id = $1::text
HAVING count(*) > 0
`

type GetReadingPeriodRow struct {
	FirstReadingAt time.Time
	LastReadingAt  time.Time
}

// First and last source timestamp, for all meters or one. Returns no row
// when there are no readings.
func (q *Queries) GetReadingPeriod(ctx context.Context, meterID *string) (GetReadingPeriodRow, error) {
	row := q.db.QueryRow(ctx, getReadingPeriod, meterID)
	var i GetReadingPeriodRow
	err := row.Scan(&i.FirstReadingAt, &i.LastReadingAt)
	return i, err
}

const getSourceTotals = `-- name: GetSourceTotals :one

SELECT (SELECT count(*) FROM meters)                                    AS meters_count,
       (SELECT count(*) FROM readings)                                  AS readings_count,
       (SELECT coalesce(sum(consumption_kwh), 0) FROM readings)::float8 AS total_consumption_kwh
`

type GetSourceTotalsRow struct {
	MetersCount         int64
	ReadingsCount       int64
	TotalConsumptionKwh float64
}

// Dashboard summary (internal/dashboard).
func (q *Queries) GetSourceTotals(ctx context.Context) (GetSourceTotalsRow, error) {
	row := q.db.QueryRow(ctx, getSourceTotals)
	var i GetSourceTotalsRow
	err := row.Scan(&i.MetersCount, &i.ReadingsCount, &i.TotalConsumptionKwh)
	return i, err
}
