// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meters.sql

package dbgen

import (
	"context"
	"time"
)

const countMeters = `-- name: CountMeters :one
WITH current_run AS (
    SELECT id FROM analysis_runs
    WHERE status = 'COMPLETED'
    ORDER BY completed_at DESC, id DESC
    LIMIT 1
)
SELECT count(*)
FROM meters m
LEFT JOIN current_run c ON true
LEFT JOIN analysis_meter_results mr ON mr.analysis_run_id = c.id AND mr.meter_id = m.meter_id
WHERE ($1::text IS NULL OR strpos(lower(m.meter_id), lower($1::text)) > 0)
  AND ($2::text IS NULL OR mr.computed_status = $2::text)
`

type CountMetersParams struct {
	Search         *string
	ComputedStatus *string
}

func (q *Queries) CountMeters(ctx context.Context, arg CountMetersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMeters, arg.Search, arg.ComputedStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMeterOverview = `-- name: GetMeterOverview :one
WITH current_run AS (
    SELECT id, completed_at FROM analysis_runs
    WHERE status = 'COMPLETED'
    ORDER BY completed_at DESC, id DESC
    LIMIT 1
),
totals AS (
    SELECT coalesce(sum(consumption_kwh), 0)::float8 AS total_consumption_kwh,
           count(*)                                  AS readings_count
    FROM readings
    WHERE meter_id = $1
)
SELECT m.meter_id,
       t.total_consumption_kwh,
       t.readings_count,
       c.id           AS analysis_run_id,
       c.completed_at AS analysis_completed_at,
       mr.computed_status
FROM meters m
CROSS JOIN totals t
LEFT JOIN current_run c ON true
LEFT JOIN analysis_meter_results mr ON mr.analysis_run_id = c.id AND mr.meter_id = m.meter_id
WHERE m.meter_id = $1
`

type GetMeterOverviewRow struct {
	MeterID             string
	TotalConsumptionKwh float64
	ReadingsCount       int64
	AnalysisRunID       *int64
	AnalysisCompletedAt *time.Time
	ComputedStatus      *string
}

func (q *Queries) GetMeterOverview(ctx context.Context, meterID string) (GetMeterOverviewRow, error) {
	row := q.db.QueryRow(ctx, getMeterOverview, meterID)
	var i GetMeterOverviewRow
	err := row.Scan(
		&i.MeterID,
		&i.TotalConsumptionKwh,
		&i.ReadingsCount,
		&i.AnalysisRunID,
		&i.AnalysisCompletedAt,
		&i.ComputedStatus,
	)
	return i, err
}

const listCurrentMeterFindings = `-- name: ListCurrentMeterFindings :many
SELECT a.id, a.type, a.severity, a.confidence, a.priority, a.consumption_deviation_pct,
       a.started_at, a.last_observed_at, a.recommended_action, a.reason
FROM anomalies a
WHERE a.meter_id = $1
  AND a.analysis_run_id = (
      SELECT id FROM analysis_runs
      WHERE status = 'COMPLETED'
      ORDER BY completed_at DESC, id DESC
      LIMIT 1
  )
ORDER BY a.priority
`

type ListCurrentMeterFindingsRow struct {
	ID                      int64
	Type                    string
	Severity                string
	Confidence              float64
	Priority                int32
	ConsumptionDeviationPct float64
	StartedAt               time.Time
	LastObservedAt          time.Time
	RecommendedAction       string
	Reason                  string
}

func (q *Queries) ListCurrentMeterFindings(ctx context.Context, meterID string) ([]ListCurrentMeterFindingsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentMeterFindings, meterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentMeterFindingsRow
	for rows.Next() {
		var i ListCurrentMeterFindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Severity,
			&i.Confidence,
			&i.Priority,
			&i.ConsumptionDeviationPct,
			&i.StartedAt,
			&i.LastObservedAt,
			&i.RecommendedAction,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeterReadings = `-- name: ListMeterReadings :many
SELECT reading_timestamp,
       consumption_kwh::float8 AS consumption_kwh,
       voltage_v::float8       AS voltage_v,
       current_a::float8       AS current_a,
       power_factor::float8    AS power_factor,
       source_status
FROM readings
WHERE meter_id = $1
  AND ($2::timestamp IS NULL OR reading_timestamp >= $2::timestamp)
  AND ($3::timestamp IS NULL OR reading_timestamp < $3::timestamp)
ORDER BY reading_timestamp
LIMIT $4
`

type ListMeterReadingsParams struct {
	MeterID  string
	FromTs   *time.Time
	ToTs     *time.Time
	RowLimit int32
}

type ListMeterReadingsRow struct {
	ReadingTimestamp time.Time
	ConsumptionKwh   float64
	VoltageV         float64
	CurrentA         float64
	PowerFactor      float64
	SourceStatus     string
}

// Half-open range [from_ts, to_ts) on source wall-clock time (ADR-008).
func (q *Queries) ListMeterReadings(ctx context.Context, arg ListMeterReadingsParams) ([]ListMeterReadingsRow, error) {
	rows, err := q.db.Query(ctx, listMeterReadings,
		arg.MeterID,
		arg.FromTs,
		arg.ToTs,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMeterReadingsRow
	for rows.Next() {
		var i ListMeterReadingsRow
		if err := rows.Scan(
			&i.ReadingTimestamp,
			&i.ConsumptionKwh,
			&i.VoltageV,
			&i.CurrentA,
			&i.PowerFactor,
			&i.SourceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeters = `-- name: ListMeters :many

WITH current_run AS (
    SELECT id FROM analysis_runs
    WHERE status = 'COMPLETED'
    ORDER BY completed_at DESC, id DESC
    LIMIT 1
),
totals AS (
    SELECT meter_id, sum(consumption_kwh)::float8 AS total_consumption_kwh
    FROM readings
    GROUP BY meter_id
),
top_finding AS (
    SELECT DISTINCT ON (a.meter_id)
           a.meter_id, a.id, a.type, a.severity, a.confidence, a.priority, a.consumption_deviation_pct
    FROM anomalies a
    JOIN current_run c ON a.analysis_run_id = c.id
    ORDER BY a.meter_id, a.priority
),
page AS (
    SELECT m.meter_id,
           coalesce(t.total_consumption_kwh, 0)::float8 AS total_consumption_kwh,
           mr.computed_status,
           f.id                        AS anomaly_id,
           f.type                      AS anomaly_type,
           f.severity                  AS severity,
           f.confidence                AS confidence,
           f.priority                  AS priority,
           f.consumption_deviation_pct AS variation_pct,
           CASE f.severity WHEN 'HIGH' THEN 3 WHEN 'MEDIUM' THEN 2 WHEN 'LOW' THEN 1 ELSE 0 END AS severity_rank
    FROM meters m
    LEFT JOIN totals t ON t.meter_id = m.meter_id
    LEFT JOIN current_run c ON true
    LEFT JOIN analysis_meter_results mr ON mr.analysis_run_id = c.id AND mr.meter_id = m.meter_id
    LEFT JOIN top_finding f ON f.meter_id = m.meter_id
    WHERE ($5::text IS NULL OR strpos(lower(m.meter_id), lower($5::text)) > 0)
      AND ($6::text IS NULL OR mr.computed_status = $6::text)
)
SELECT meter_id, total_consumption_kwh, computed_status, anomaly_id, anomaly_type,
       severity, confidence, priority, variation_pct
FROM page
ORDER BY
    CASE WHEN $1::text = 'consumption' AND $2::bool = false THEN total_consumption_kwh END ASC,
    CASE WHEN $1::text = 'consumption' AND $2::bool = true THEN total_consumption_kwh END DESC,
    CASE WHEN $1::text = 'variation' AND $2::bool = false THEN abs(variation_pct) END ASC NULLS LAST,
    CASE WHEN $1::text = 'variation' AND $2::bool = true THEN abs(variation_pct) END DESC NULLS LAST,
    CASE WHEN $1::text = 'severity' AND $2::bool = false THEN severity_rank END ASC,
    CASE WHEN $1::text = 'severity' AND $2::bool = true THEN severity_rank END DESC,
    CASE WHEN $1::text = 'severity' THEN priority END ASC NULLS LAST,
    CASE WHEN $1::text = 'meter_id' AND $2::bool = true THEN meter_id END DESC,
    meter_id ASC
LIMIT $4 OFFSET $3
`

type ListMetersParams struct {
	SortKey        string
	SortDesc       bool
	RowOffset      int32
	RowLimit       int32
	Search         *string
	ComputedStatus *string
}

type ListMetersRow struct {
	MeterID             string
	TotalConsumptionKwh float64
	ComputedStatus      *string
	AnomalyID           *int64
	AnomalyType         *string
	Severity            *string
	Confidence          *float64
	Priority            *int32
	VariationPct        *float64
}

// Meter list, detail and readings (internal/meter). "Current" analytical
// state always comes from the latest COMPLETED analysis run.
// One query for the whole page (no per-meter queries). Sort keys are fixed
// whitelisted values chosen by the caller; user text never reaches SQL
// structure. Variation sorts by magnitude; meters without a value sort last.
func (q *Queries) ListMeters(ctx context.Context, arg ListMetersParams) ([]ListMetersRow, error) {
	rows, err := q.db.Query(ctx, listMeters,
		arg.SortKey,
		arg.SortDesc,
		arg.RowOffset,
		arg.RowLimit,
		arg.Search,
		arg.ComputedStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMetersRow
	for rows.Next() {
		var i ListMetersRow
		if err := rows.Scan(
			&i.MeterID,
			&i.TotalConsumptionKwh,
			&i.ComputedStatus,
			&i.AnomalyID,
			&i.AnomalyType,
			&i.Severity,
			&i.Confidence,
			&i.Priority,
			&i.VariationPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const meterExists = `-- name: MeterExists :one
SELECT EXISTS (SELECT 1 FROM meters WHERE meter_id = $1)
`

func (q *Queries) MeterExists(ctx context.Context, meterID string) (bool, error) {
	row := q.db.QueryRow(ctx, meterExists, meterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
